name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full Git history is available

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Change to your Node.js version if needed

      - name: Install dependencies
        run: npm install  # Using npm directly instead of bahmutov/npm-install

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the full commit history is available

      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated from v3 to v4
        with:
          name: production-files
          path: ./dist

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Switch to main branch
        run: git checkout main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
